In [5]:
import numpy as np

def hebbian_learning_rule(input_pat,wt_matrix):
    return wt_matrix+np.outer(input_pat,input_pat)
    
def perceptron_learning_rule(input_pat,target,wt_vector,lr):
    prediction=np.dot(wt_vector,input_pat)
    error=target-prediction
    return wt_vector+lr*error*input_pat

def delta_learning_rule(input_pat, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pat)
    error = target - prediction
    return weight_matrix + learning_rate * np.outer(error, input_pat)

def correlation_learning_rule(input_pat, weight_matrix):
    return weight_matrix + np.outer(input_pat, input_pat)

def out_star_learning_rule(input_pat, weight_matrix, learning_rate):
    return weight_matrix + learning_rate * np.outer(input_pat, input_pat)


input_pattern=np.array([0.2,0.8,0.5])
target=1;
input_size=3;

hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size, input_size)

print("Hebbian Weights:",hebbian_weights)
print("\nPerceptron Weights:",perceptron_weights)
print("\nDelta Weights:",delta_weights)
print("\nCorrelation Weights:",correlation_weights)
print("\nOut Star Weights:",out_star_weights)


hebbian_weights_updated = hebbian_learning_rule(input_pattern, hebbian_weights)

perceptron_weights_updated = perceptron_learning_rule(input_pattern, target,perceptron_weights, 0.1)

delta_weights_updated = delta_learning_rule(input_pattern, target, delta_weights,learning_rate=0.1)

correlation_weights_updated = correlation_learning_rule(input_pattern, correlation_weights)

out_star_weights_updated = out_star_learning_rule(input_pattern, out_star_weights,learning_rate=0.1)

# Display updated weights
print("Hebbian Updated Weights:", hebbian_weights_updated)
print("\nPerceptron Updated Weights:", perceptron_weights_updated)
print("\nDelta Updated Weights:", delta_weights_updated)
print("\nCorrelation Updated Weights:",correlation_weights_updated)
print("\nOut Star Updated Weights:",out_star_weights_updated)

Hebbian Weights: [[0.88816113 0.01065722 0.36066333]
 [0.29346402 0.57816006 0.29029198]
 [0.55731848 0.82742882 0.62843701]]

Perceptron Weights: [0.85885947 0.44631155 0.55885758]

Delta Weights: [[0.37493304 0.10127491 0.70773273]
 [0.75917324 0.0699873  0.89288665]
 [0.40532007 0.0575983  0.02432635]]

Correlation Weights: [[0.91422495 0.62744041 0.01845102]
 [0.78670354 0.30646764 0.35048385]
 [0.79064732 0.42675844 0.69774734]]

Out Star Weights: [[0.2955298  0.41037247 0.56583023]
 [0.03914367 0.82648236 0.39605206]
 [0.20800731 0.15983001 0.71580567]]
Hebbian Updated Weights: [[0.92816113 0.17065722 0.46066333]
 [0.45346402 1.21816006 0.69029198]
 [0.65731848 1.22742882 0.87843701]]

Perceptron Updated Weights: [0.86269447 0.46165155 0.56844508]

Delta Updated Weights: [[0.38473558 0.14048507 0.73223909]
 [0.76608789 0.09764587 0.91017326]
 [0.42253395 0.12645383 0.06736106]]

Correlation Updated Weights: [[0.95422495 0.78744041 0.11845102]
 [0.94670354 0.94646764 0.75048385]
 